name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或是你的分支名稱

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          CI=false npm run build  # <--- 在這裡加上 CI=false

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # React 編譯後的資料夾
          branch: gh-pages # 部署到的分支
